### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by ghost** [TehShrike/Sublime-AlphanumericMarkdownFootnote#1]
Hey,

I successfully tested my install w/ test.py (console said _Passing!_)but AlphanumericMarkdownFootnote doesn't seem to work : nothing happens when I press ctrl+alt+f and no trace of it in the Package Settings Menu

I'm under windows&linux installs, using AcademicMarkdown, MarkdownEditing, Citer & Pandoc. Installed AlphanumericMarkdownFootnote through PackageControl and then manually.

Looking at the Sublime console on startup, got this meaningful output :

> File "C:\###\Roaming\Sublime Text 3\Packages\Sublime-AlphanumericMarkdownFootnote-master\test.py", line 1, in <module>
>     from FootnoteFunctions import insert_footnote, find_enclosing_footnote_id, find_footnote_marker_position, get_footnote_marker_id_at_position, get_footnote_body_position
> ImportError: No module named 'FootnoteFunctions'

As it look quite great, I do hope for an answer :D
Cheers !

**Comment by TehShrike** [comment]
Huh, I am also seeing this error on my Windows machine.

Most of my testing was done on macOS - I did test the initial versions on my Windows 8 machine, but didn't re-test on Windows before publishing the last couple versions.

Sublime isn't intended to load the `test.py` file, I'm not sure why it would try, or why it would only try on Windows.

I won't be able to look into this very soon - but if you can figure out how to tell Sublime that it should only be directly loading the `AlphanumericMarkdownFootnote.py` file, I can apply the fix and deploy pretty quickly.

**Comment by gmalone** [comment]
Same issue here.  The plugin does not work in Win 10 (updated latest 2018.09.15).  ST3 latest.  No response from hotkey(s).  No apparent menu entry either (MarkdownFootnotes had a menu entry).  Any intent to fix?  Thanks.

**Comment by TehShrike** [comment]
My client only uses macOS, so I'm not motivated to spend the time it would take to support Windows.

I'm open to pull requests, though.

**Comment by gmalone** [comment]
Understood.  Thanks for the kind reply.

Greg Malone
Santa Fe, New Mexico
